# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "LatestRelease" ]
  pull_request:
    branches: [ "LatestRelease" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    
    #- uses: browser-actions/setup-chrome@v1
    #- run: chrome --version

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        
    - name: Go Tests
      run: go test -v ./tests/utils/random/./...
      
    - name: Go Benchmarks
      run: go test -v -bench=./tests/utils/random/./... ./tests/utils/random/./...
